[phases.setup]
nixPkgs = ['...', 'maven']

[phases.build]
cmds = ['chmod +x mvnw', './mvnw clean package -DskipTests']

[start]
cmd = 'java -Dserver.port=$PORT -jar target/proyectoingweb-0.0.1-SNAPSHOT.jar'
